// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddShortcut(arg1:string,arg2:string):Promise<main.shortcuts>;

export function ExportShortcuts():Promise<void>;

export function GetShortcuts():Promise<main.shortcuts>;

export function GetVersion():Promise<string>;

export function ImportShortcuts():Promise<void>;

export function RemoveShortcut(arg1:string):Promise<void>;
