// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {utils} from '../models';

export function AddSavedDirectory(arg1:string,arg2:string):Promise<void>;

export function AddShortcut(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, utils.ShortcutData>>;

export function ApplyShortcut(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function ClearRunHistory():Promise<void>;

export function CliExists(arg1:string):Promise<boolean>;

export function DuplicateShortcut(arg1:string):Promise<Record<string, utils.ShortcutData>>;

export function ExportShortcuts():Promise<void>;

export function GetConfig():Promise<utils.AppConfig>;

export function GetRunHistory():Promise<Array<utils.RunHistoryEntry>>;

export function GetShortcuts():Promise<Record<string, utils.ShortcutData>>;

export function GetStartOnBoot():Promise<boolean>;

export function GetVersion():Promise<string>;

export function ImportShortcuts():Promise<void>;

export function RemoveSavedDirectory(arg1:string):Promise<void>;

export function RemoveShortcut(arg1:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SetPreferredTerminal(arg1:string):Promise<void>;

export function SetStartOnBoot(arg1:boolean):Promise<void>;

export function TogglePinShortcut(arg1:string):Promise<void>;

export function UpdateShortcut(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;
