// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddShortcut(arg1, arg2) {
  return window['go']['main']['App']['AddShortcut'](arg1, arg2);
}

export function GetShortcuts() {
  return window['go']['main']['App']['GetShortcuts']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RemoveShortcut(arg1) {
  return window['go']['main']['App']['RemoveShortcut'](arg1);
}
