// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddShortcut(arg1, arg2) {
  return window['go']['main']['App']['AddShortcut'](arg1, arg2);
}

export function CliExists(arg1) {
  return window['go']['main']['App']['CliExists'](arg1);
}

export function ExportShortcuts() {
  return window['go']['main']['App']['ExportShortcuts']();
}

export function GetShortcuts() {
  return window['go']['main']['App']['GetShortcuts']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportShortcuts() {
  return window['go']['main']['App']['ImportShortcuts']();
}

export function RemoveShortcut(arg1) {
  return window['go']['main']['App']['RemoveShortcut'](arg1);
}
