// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSavedDirectory(arg1, arg2) {
  return window['go']['main']['App']['AddSavedDirectory'](arg1, arg2);
}

export function AddShortcut(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddShortcut'](arg1, arg2, arg3, arg4);
}

export function ApplyShortcut(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyShortcut'](arg1, arg2, arg3);
}

export function ClearRunHistory() {
  return window['go']['main']['App']['ClearRunHistory']();
}

export function CliExists(arg1) {
  return window['go']['main']['App']['CliExists'](arg1);
}

export function DuplicateShortcut(arg1) {
  return window['go']['main']['App']['DuplicateShortcut'](arg1);
}

export function ExportShortcuts() {
  return window['go']['main']['App']['ExportShortcuts']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetRunHistory() {
  return window['go']['main']['App']['GetRunHistory']();
}

export function GetShortcuts() {
  return window['go']['main']['App']['GetShortcuts']();
}

export function GetStartOnBoot() {
  return window['go']['main']['App']['GetStartOnBoot']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportShortcuts() {
  return window['go']['main']['App']['ImportShortcuts']();
}

export function RemoveSavedDirectory(arg1) {
  return window['go']['main']['App']['RemoveSavedDirectory'](arg1);
}

export function RemoveShortcut(arg1) {
  return window['go']['main']['App']['RemoveShortcut'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetPreferredTerminal(arg1) {
  return window['go']['main']['App']['SetPreferredTerminal'](arg1);
}

export function SetStartOnBoot(arg1) {
  return window['go']['main']['App']['SetStartOnBoot'](arg1);
}

export function TogglePinShortcut(arg1) {
  return window['go']['main']['App']['TogglePinShortcut'](arg1);
}

export function UpdateShortcut(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateShortcut'](arg1, arg2, arg3, arg4);
}
